version: "2.0"
services:
    jdk:
        image: registry.cn-hangzhou.aliyuncs.com/alirobot/oraclejdk8-nscd
        ports: ["8080:8080"]
        volumes:
            - "/mnt/demo:/usr/local/project"
        environment:
            TZ: Asia/Shanghai
            WORKDIR: /usr/local/project
        command: []
        entrypoint: [java,-jar,/usr/local/project/demo-0.0.1-SNAPSHOT.jar]
        restart: always